### ISSUE TITLE
Can we setup the length for Scanner.py

### ISSUE THREAD

**Issue by wuy24** [gaolabtools/scNanoGPS#1]
Hello, I read your bioRxiv paper of "Delineating genotypes and phenotypes of individual cells from longread
single cell transcriptomes" and would like to try your scNanoGPS software for our ONT single cell data. 
For the step2 Scanner, you setup to scan the first and last 100 nucleotides of reads to recognize TruSeq Read 1 and PolyA by default. I wonder if  we can setup first and last 150 or 200 nucleotides for scanning. Because when I use the default parameter, majority of my reads are filtered out although the sequence quality looks good.
Look forward to your reply! Thank you!

**Comment by shiauck** [comment]
Hi,
Thanks for the feedback.

We have added a new parameter (--scanning_region) for setting scanning region length.
Please check the updated README and make a new clone.

We really appreciate your suggestion.
Thanks in advance.

**Comment by wuy24** [comment]
Thank you very much for your quick response and update!
