### ISSUE TITLE
Curator script taking huge time

### ISSUE THREAD

**Issue by TR13** [gaolabtools/scNanoGPS#11]
Hi, I am using scNanoGPS. I have finished the initial steps and am now running the curator.py script. I has been running and it seems it will take lot of time to finish.
![Screen Shot 2023-09-22 at 9 47 26 AM](https://github.com/gaolabtools/scNanoGPS/assets/7554850/3905e111-4f6c-4681-ade0-acfd8237e993)

Fastq file size - 109GB

Commands 
python3 scanner.py -i fastq_pass/ -d scNanoGPS_res -t 16

python3 ../../assigner.py -i barcode_list.tsv.gz -d scNanoGPS_res -t 16 --forced_no 10000

python3 ../../curator.py -d scNanoGPS_res -t 16 --ref_genome Homo_sapiens.GRCh38.dna.toplevel.fa --keep_meta 1

Is there any way to reduce the processing time? Is my run going well?

**Comment by shiauck** [comment]
Hi,

According to my experience, it takes ~5 days to run curator containing ~80M Nanopore reads.
But it still depends on the sample condition.
For example, If your sample contains a lot of rRNAs, then the curator would kind of getting stuck on rRNA gene regions.
So if you're not interested in rRNA, probably you can skip uninteresting regions to save time by using parameter "--exc_bed".

Besides, I notice that you're using "keep_meta".
In the normal condition, I'll recommend not using this for some reasons:
(1) some meta files occupy tons of storage space, like SAM file. It might potentially cause some problems.
(2) This is for debugging purpose. I never check whether the meta files using the same file name or not, meaning that it could create clerical errors.

Hope this helps.

Regards,
Cheng-Kai

**Comment by TR13** [comment]
> Hi,
> 
> According to my experience, it takes ~5 days to run curator containing ~80M Nanopore reads. But it still depends on the sample condition. For example, If your sample contains a lot of rRNAs, then the curator would kind of getting stuck on rRNA gene regions. So if you're not interested in rRNA, probably you can skip uninteresting regions to save time by using parameter "--exc_bed".
> 
> Besides, I notice that you're using "keep_meta". In the normal condition, I'll recommend not using this for some reasons: (1) some meta files occupy tons of storage space, like SAM file. It might potentially cause some problems. (2) This is for debugging purpose. I never check whether the meta files using the same file name or not, meaning that it could create clerical errors.
> 
> Hope this helps.
> 
> Regards, Cheng-Kai

Thanks for your response. I had used keep_meta as i was just trying to follow the script line by line in test run. I forgot to remove it in final execution. I have restarted curator.py without --keep_meta and have used --exc_bed rRNA
