### ISSUE TITLE
Curator - IndexError: list index out of range

### ISSUE THREAD

**Issue by reJELIN** [gaolabtools/scNanoGPS#14]
Hello, I keep getting this error but i have no idea how to solve it ,this is the command line :

```
python3 /mypath/userdata/user_name/bin/scNanoGPS/curator.py \
--fq_name /mypath/scNanoGPS/scanner_res/processed.fastq.gz \
-b /mypath/scNanoGPS/scanner_res/barcode_list.tsv.gz \
--CB_count /mypath/scNanoGPS/assigner_res/CB_counting.tsv.gz \
--CB_list /mypath/scNanoGPS/assigner_res/CB_merged_list.tsv.gz \
--ref_genome /mypath/scNanoGPS/com/input/ensembl_gtf_fasta/fasta/genome.fa \
--idx_genome /mypath/scNanoGPS/genome/genome.mmi \
-d /mypath/scNanoGPS/curator_res/ \
--tmp_dir /mypath/scNanoGPS/curator_res/tmp/ \
-t 30 \
--minimap2 /myhpath/userdata/my_user_name/conda_install/miniconda3/envs/scNanoGPS/bin/minimap2 \
--samtools/mypath/userdata/my_user_name/conda_install/miniconda3/envs/scNanoGPS/bin/samtools \
--spoa /my_path/userdata/my_user_name/conda_install/miniconda3/envs/scNanoGPS/bin/spoa
```

I got a long list of what i suppose is a barcode or a number keeping track of barcodes then it goes like this:

```
Time stamp: Mon, 06 Nov 2023 23:41:44 

Time elapse: 9 : 34 : 54.54
Mapping reads for each individual cell barcode ...
Traceback (most recent call last):
  File "/mnt/beegfs/userdata/r_jelin/bin/scNanoGPS/curator.py", line 128, in <module>
    fq_pref = fq.split(".fastq.gz")[0].split(options.tmp_dir)[1].split('/')[1]
IndexError: list index out of range
```

Could you help me know what i did wrong there ?

**Comment by shiauck** [comment]
Hi,

Could you verify your command line for me?
I notice several typos there.
Thanks.

Regards,
Cheng-Kai

**Comment by reJELIN** [comment]
Yeah don't mind about it, I hide the real path with fake path but there is no typo error in my original script.

**Comment by shiauck** [comment]
I see.

The error message means that the python code could not extract cell barcode as a prefix.
Could you try to remove the last slash when using --tmp_dir ?
"--tmp_dir /mypath/scNanoGPS/curator_res/tmp"
Thanks.

Regards,
Cheng-Kai

**Comment by reJELIN** [comment]
Nice ! I thought that too, so i did try it this morning without the last slash, i should have a result soon !

I'll keep you informed !

Thanks,

Best regards,
JELIN

**Comment by shiauck** [comment]
Cool.
Glad to help.

Regards,
Cheng-Kai

**Comment by reJELIN** [comment]
I can confirm, it was the last slash of the --tmp-dir argument that leaded to this error. It work now !

Again thank you for your help !

Best regards,
JELIN
