### ISSUE TITLE
HELP - report_expression

### ISSUE THREAD

**Issue by reJELIN** [gaolabtools/scNanoGPS#15]
Hello,

First, I  successfully, thank to your help, pass the curator step BUT i'm very confuse about the next step.

I'm kind of confuse because you're saying : We merged both singleton BAMs with consensus BAMs to formal a final BAMs as curated data. What is the name of the final BAM merged file ?

i'm currently trying the report_expression step.

what is the filtered_barcode_list.txt from the sel_bc_o argument ? how to i obtain it ?

should I always keep the same tmp folder for --tmp_dir argument ?

```
python3 /path/to/python/reporter_expression.py \
-d /fake/path/scNanoGPS/scanner_res \
--tmp_dir /fake/pathscNanoGPS/tmp_2 \
--gtf /fake/path/genes/genes.gtf \
-o /fake/path/scanner_res/matrix.tsv \
--min_gene_no 200 \
--featurecounts /fake/path/miniconda3/envs/scNanoGPS/bin/featureCounts \
-t 5
```
All my result are in the scanner_res folder:

- assigner.log.txt  
- barcode_list.tsv.gz 
-  CB_counting.tsv.gz  
- CB_log10_dist.png  
- CB_merged_dist.tsv.gz  
- CB_merged_list.tsv.gz  
- curator.log.txt  
- processed.fastq.gz  
- reporter_expression.log.txt 
-  scanner.log.txt

here is the log.txt from report_expression.log.txt:

```
Reading data from <STDIN> for featureCounts ...


ERROR: no valid SAM or BAM file is received from <STDIN>
```

Thank you again for your help, i'm very excited to be able to analyse results from your pipeline when it will work !

**Comment by shiauck** [comment]
Hi,

The name of the final BAM merged file: "<BC>.curated.minimap2.bam"

After you run the reporter_expression.py, the script filters out the cell barcode having less than a minimal number of genes (default: 300), and generates the final barcode list "filtered_barcode_list.txt"

The temporal files for reporters are stored under <tmp_dir>, so please keep the folder name the same to prevent the following scripts miss the data source.

The report_expression.log.txt shows that the script couldn't find the bam files stored under <tmp_dir>

Please let me know if you have any questions.

Regards,
Cheng-Kai
