### ISSUE TITLE
Curator Counting Table Not Generated

### ISSUE THREAD

**Issue by BenneyMRArgue** [gaolabtools/scNanoGPS#22]
I have really appreciated having this tool to use on my long read data, thanks for developing it! 

I had a question regarding the output from the Curator step. I have been able to run the curator with consensus for my samples, however the output all remains in the temporary folder, with six files for each cell barcode. No .tsv files were generated in the temporary folder or anywhere else. No error happened, and the job completed well within the time frame I gave it, so it does not appear to have ended prematurely. 

I'd like to use the Reporter scripts, but the input needed appears to be a matrix which is not created for any of my samples. Do you know why this might be, or any alternative ways to ensure that the final .tsv file is generated? Otherwise, is there a way for me to use the Reporter without this matrix input?

Thanks,
-Benney

**Comment by shiauck** [comment]
Hi Benney,

The curator is designed for aligning reads back to reference genome and curation among the reads, and finally produce the curated bam files stored under temporary folder.
The reporters are using bam files under temporary folder to produce matrices files storing under scNanoGPS_res, by default.
Please try this: (or run_scNanoGPS.sh line 21)
```
python3 <path/to/scNanoGPS/>reporter_expression.py -d <path/to/scNanoGPS/result/> --tmp_dir <path/to/scNanoGPS/temporary/folder/> --gtf <path/to/GTF/file> -t <CPU_core_number>
```
After reporter, the matrix.tsv should be found under <path/to/scNanoGPS/result/>.
In addition, please make sure featureCounts is executable under your path.
Hope this helps.

Regards,
Cheng-kai

**Comment by BenneyMRArgue** [comment]
Hi Cheng-kai,

Thanks so much for clarifying, this answers my question.

-Benney
