### ISSUE TITLE
request of an option to output unassigned read fastq file at the scanner and assigner process

### ISSUE THREAD

**Issue by myano-fgin** [gaolabtools/scNanoGPS#24]
Hi Cheng-Kai,

This is the request.

if you could add an option to output unassigned read fastq file at the scanner process and the assigner process, the option will be helpful to investigate/check the reason of unassignment in case the detecting rates are lower then expected.

At this moment, I am able to get the same information by differencial comparison between input fastq data and processed.fastq / the barcode_list.  But it is helpful if I can just use the option without doing anyfurther process after the scanner and the assigner.

Best regards,
Minoru

**Comment by shiauck** [comment]
Hi Minoru,

It's a good suggestion.
I'll discuss with my mentor about this.
You can try [this tool](https://github.com/lh3/seqtk) to extract un-assigned reads if needed.
Thank you for your suggestion.

Regards,
Cheng-Kai

**Comment by myano-fgin** [comment]
Hi Cheng-Kai,

Thank you for regarding my request as a good suggestion.
But, I do not mind that your team decide that it is not a useful option at the end.

At this moment, I will get the un-assigned reads by the seqtk or by other tools by my hands.

Best regards,
Minoru
