### ISSUE TITLE
Problem when running reporter_SNV.py

### ISSUE THREAD

**Issue by cariocow** [gaolabtools/scNanoGPS#25]
Hi Cheng-Kai,

Thanks for developing the scNanogps tool. 

When i run the reporter_SNV.py, I got the following problem:
"index: the file is not BGZF compressed, cannot index: /path/longshot.output.ATCCATTCAATACGCT.vcf.gz"
or either 
"index: failed to open /path/longshot.output.CCTCCAACATTGGGAG.vcf.gz"

Would you please help to solve this? Many thanks!

Best 
Cario

**Comment by shiauck** [comment]
Hi Cario,

The error is due to compression of vcf file.
Please make sure:
(1) your python environment has Bio::bgzf installed on it
(2) your environment can reach bcftools
(3) your environment can reach tabix
Thanks.

Regards,
Cheng-Kai
