### ISSUE TITLE
Quick question about application of master Fastq file

### ISSUE THREAD

**Issue by hyeon9** [gaolabtools/scNanoGPS#26]
Hi Cheng-Kai,

First of all, thank you so much for your shiny tool for sc long read data.
Now I've wanted to investigate their isoform diversity. 
So, as I think (after reading your paper carefully), the master fastq file or merged consensus bam (using samtools merge) could be used in Flair to make novel gtf file.
Could you please give me your opinion about the strategy?

Thank you!

**Comment by shiauck** [comment]
Hi,

Thank you for sharing us your idea.
I never try this way, and theoretically it should work.
I'm grateful to hear you sharing your trial results.
Thanks.

Regards,
Cheng-Kai
