### ISSUE TITLE
summary.txt of example input data

### ISSUE THREAD

**Issue by myano-fgin** [gaolabtools/scNanoGPS#29]
Hi Cheng-kai,

Could you confirm that the summary.txt below for example data is correct?

While using the scNanoGPS with my test data, I am also using it with the example data (demo data/toy data) in GitHub page.  I come to the final 5 Reporter process without error.
I would like to know that the result is correct or not, so that I am confident that the installation of scNanoGPS and the handling commands are correct.

```
ead yield:                  7731
Valid read number:           7731
Detecting rate:              100.0%

Median read length:          821.0
Mean read length:            984.92
Maximal read length:         5546
Median cell barcode quality: 23.31
Mean cell barcode quality:   22.74

Cell number:                 56
Raw reads per cell:          138.05
UMI counts:                  7047
Median UMI counts per cell:  124.0
Mean UMI counts per cell:    125.84
Median gene number:          53.0
Mean gene number:            49.36

Exonic:                      13.18%
Intronic:                    70.94%
Intergenic:                  15.88%
```

Best regards,
Minoru

**Comment by shiauck** [comment]
Hi Minoru,

The result looks complete.
It should be correct I think.

Regards,
Cheng-Kai

**Comment by myano-fgin** [comment]
Thanks for the confirmation, Cheng-Kai !!
Minoru
