### ISSUE TITLE
header of CB_merged_list.tsv.gz is weird when using force cell option

### ISSUE THREAD

**Issue by donginLee37** [gaolabtools/scNanoGPS#34]
Hi,

When I ran "assigner.py" forced_no option, the header of CB_merged_list.tsv.gz is weird like a picture of below:
![Screenshot 2024-05-30 154040](https://github.com/gaolabtools/scNanoGPS/assets/91251785/a74b2029-bab6-49b1-8289-cbd04f7943a8)
the 1:1 was added next to the header. But when I removed the forced_no option, it was fine.
For now I manually move 1:1 to the next line before going to next steps, but would it be solved?

Thanks.

**Comment by shiauck** [comment]
Hi,

Thanks for the bug report.
I've patched the assigner.py.
Please clone it again.

Regards,
Cheng-Kai

**Comment by donginLee37** [comment]
Hi,

Thanks for looking into it and fixing this problem.
I tested with a new file and worked well.

I will close this issue, then.

Best,
Dongin
