### ISSUE TITLE
Problem of running reporter_SNV

### ISSUE THREAD

**Issue by donginLee37** [gaolabtools/scNanoGPS#35]
Hi,

When I ran running the reporter_SNV.py, I got some errors like below:

Longshot: Calling SNV in GAGCTAGCACTAAATC ...
Longshot spend 0:1:32.99 on GAGCTAGCACTAAATC
[E::hts_open_format] Failed to open file "/OUT/tmp/longshot.output.GAGCTAGCACTAAATC.vcf" : No such file or directory
Failed to read from /OUT/tmp/longshot.output.GAGCTAGCACTAAATC.vcf: No such file or directory
index: failed to open /OUT/tmp/longshot.output.GAGCTAGCACTAAATC.vcf.gz

OR

Longshot: Calling SNV in TGTTATGAGCTTAGTA ...
Longshot spend 0:1:35.85 on TGTTATGAGCTTAGTA
index: failed to open /OUT/tmp/longshot.output.TGTTATGAGCTTAGTA.vcf.gz
[E::hts_open_format] Failed to open file "/OUT/tmp/longshot.output.TGTTATGAGCTTAGTA.vcf" : No such file or directory
Failed to read from /OUT/tmp/longshot.output.TGTTATGAGCTTAGTA.vcf: No such file or directory

Acutally I found that the vcf files were generated and disappeared, and when I looked into the vcf files, they had proper vcf format.

I saw the previous issue similar to this, and I checked that all three tools (bgzf of biopython, samtools, and bcftools) are well installed in my conda environment.

Below command is my running command:
python3 ~/scNanoGPS/reporter_SNV.py -t 4 --ref_genome /PATH/GRCh38/fasta/genome.fa \
--annovar ~/shared/scNanoGPS/annovar/table_annovar.pl --annovar_db ~/shared/scNanoGPS/annovar/humandb/ -d /OUT/ \
--tmp_dir /OUT/tmp/

Could you help me to solve this problem?

Best,

Dongin

**Comment by shiauck** [comment]
Hi,

The error happens because you assigned output directory to your root folder and probably you don't have privilege to access the folder:
```
-d /OUT/
```

Maybe you can try this:
```
-d ./OUT/ --tmp_dir ./OUT/tmp/
```

Hope this helps.

Regards,
Cheng-Kai

**Comment by donginLee37** [comment]
Hi,

Thanks for replying and sorry to confuse you.

The "/OUT" is not directing a folder under the root, but just abbreviation of path where I have permission.
So, could you look into my issues again?

Best,

Dongin

**Comment by shiauck** [comment]
Hi Dongin,

The error message is limited for me to identify the reason why you couldn't get vcf files.
Could you please try adding the following parameter:
```
--keep_meta 1
```
This will leave your single cell temporal vcf files there without removing under your tmp folder,
so that you can check them step-by-step.

Alternatively, you can try running longshot manually.
```
longshot -F --bam /OUT/tmp/TGTTATGAGCTTAGTA.curated.minimap2.bam --ref <PATH/TO/YOUR/REF_GENOME> --min_cov 2 --min_alt_count 2 --out /OUT/tmp/longshot.output.TGTTATGAGCTTAGTA.vcf --sample_id TGTTATGAGCTTAGTA
```
Then compress the vcf file with:
```
bcftools view -0z -o /OUT/tmp/longshot.output.TGTTATGAGCTTAGTA.vcf.gz /OUT/tmp/longshot.output.TGTTATGAGCTTAGTA.vcf
```
Finally index the vcf file with:
```
bcftools index /OUT/tmp/longshot.output.TGTTATGAGCTTAGTA.vcf.gz
```

Regards,
Cheng-Kai

**Comment by donginLee37** [comment]
Hi,

Thanks for replying this time too.

It seems like the indexing step with bcftools in this script doesn't work for my case.
But by following your direction, running bcftools index manually works.

So, I tried several things, and figured out that giving two seconds before starting bcftools indexing wokrs, like below:

    #---compression---
	cmd = options.bcftools + ' view -Oz -o ' + vcf_pref + '.vcf.gz ' + vcf_pref + '.vcf &> /dev/null'
	os.system(cmd)

	time.sleep(2)
	#---indexing---
	cmd = options.bcftools + ' index ' + vcf_pref + '.vcf.gz &> /dev/null'
	os.system(cmd)

I still don't know the reason, but share this to hope this can be helpful other users with same/similar issues.

Best,

Dongin
