### ISSUE TITLE
Bio.pairwise2 has been deprecated

### ISSUE THREAD

**Issue by wanghlv** [gaolabtools/scNanoGPS#38]
Hi I've been getting warning messages about Bio.pairwise2 has been deprecated. Would you be able to consider using Bio.Align.PairwiseAligner  as suggested? in future releases. Thanks.
Best, 
Hsiao-Lin

**Comment by shiauck** [comment]
Hi Hsiao-Lin,

Thanks for the feedback.
Yes, we're preparing the next version.
We'll also update the aligning function.
Please stay tune.

Regards,
Cheng-Kai

**Comment by wanghlv** [comment]
That will be great!
