### ISSUE TITLE
CB number of gene filters

### ISSUE THREAD

**Issue by wanghlv** [gaolabtools/scNanoGPS#39]
Hi I've noticed in your paper that you've wrote "CBs with less than 300 genes are filtered out by default". However, I could not locate the corresponding codes in the scanner and Assigner steps. I only found it in the reporter_expression.py. Can I assume all CB were retained regardless of the number of UMPs or genes per cells? So I can do the typical QC in Seurat later? Thanks a lot for making this flexible tool!! Best, 
Hsiao-Lin

**Comment by shiauck** [comment]
Hi Hsiao-Lin,

Yes, the filtering for gene number is located at reporter_expression.py.
So the bam files under tmp folder hold all the raw reads.

Yes, you can do any QA/QC with Seurat even if you turn off the filtering by assigning "min_gene_no" to 1.

Hope this helps.

Regards,
Cheng-kai

**Comment by wanghlv** [comment]
Thank you! Also a quick question, could you provide the expected output for the step4, curator step? Somehow my curator step keeps getting stuck at "Loading CB_list:". I'm wondering what is happening. Thanks a lot again! 
Best, Hsiao-Lin

**Comment by shiauck** [comment]
Could you please check the file "CB_counting.tsv.gz" ?
Usually the file size should be less than one hundred MB.
The step "Loading CB_list" should not taking longer than 30 mins.

Regards,
Cheng-Kai

**Comment by wanghlv** [comment]
All my CB_counting.tsv.gz files are larger than 100 MB, the smallest is 196M and the largest is 453M. My total number of reads range from 152 million to 315 million. It's taking definitely longer than 30 min so far. Also, the loading CB_list is writing any files in the temp folder. Thanks a lot Hsiao-Lin

**Comment by shiauck** [comment]
It could take longer than 30 mins when your sample containing more than one million of reads.
The complexity is not linear but could be longer, depending on sample quality or sequencing error rate case-by-case.

Regards,
Cheng-Kai

**Comment by wanghlv** [comment]
Thank you! Best, Hsiao-Lin

**Comment by wanghlv** [comment]
Hi Cheng-Kai, I hope you don't mind if I ask another question. In the scanner step, the summary include included the 3' adapter results, would it be possible to include the 3' scanning results? Would you mind to clarify, in the scanning step, the resulting processed.fastq only includes reads that satisfy both conditions: 3' adapter sequence and polyA AND 5' adapter sequence (which also recognized the CCC/GGG during template switch)? Thanks a lot. Best, 
Hsiao-Lin

**Comment by wanghlv** [comment]
Hi Cheng-Kai, 
I also realized my step 4. curator failed after separation of reads by cell barcodes, and at the where "Mapping reads for each individual cell barcode ...
0 of 0 Done                                                  

Time stamp: Mon, 15 Jul 2024 22:01:41 

Time elapse: 1 : 57 : 8.67"

Would you know how could I fix that? Thanks so much. 

Hsiao-Lin

**Comment by shiauck** [comment]
Hi Hsiao-Lin,

The scanner scans both two tails of the reads for both TruSeq R1-CB-UMI (3' adaptor) and TSO (5' adaptor).
You can check the scanner.log.txt for the number report.
Some reads containing only 3' adaptor without 5' adaptor, which are considered as uncompleted read, are also included.

For your 0 of 0 result:
1) please try running the example to make sure your environment installed correctly.
2) please check your scanner.log.txt. Normally, the detection rate should be higher than 70% (higher than 80% is ideal).
3) please check your assigner.log.txt. The estimated cell number should be in reasonable range. In our case, the estimated cell number is usually around 2000-6000 when we targeting to 3000 cells.
4) please check the file line number of CB_merged_list.tsv.gz. In the file, each line is mapping to one cell barcode. The number of line should be equals to the estimated cell number in assigner.log.txt.

Hope this helps.

Regards,
Cheng-kai

**Comment by wanghlv** [comment]
Thank you so much for the suggestions! 

For the keeping reads in the scanner step, the number report only has information about 3' adapter. All numbers with the TSO/5'adpater are missing. Is it possible to keep only complete reads? that have both 3' and 5' adapters?

Yes I finally resolve the 0/0 result, it turns out updating from 3.8 to 3.11 worked for the example data and now I'm re running all of data again!

Thank you so much again for your prompt responses, your scNanoGPS really is best pipeline compared to others

Best
Hsiao-Lin

**Comment by wanghlv** [comment]
Hi Cheng-kai, I was able to run the example no problem, however, when I started running my own samples, in the curator step, there is still no per barcode fastq.gz written in the tmp folder. I thought it might be a file opening limit but my ulimit -S -n 65535 is set to system maximum. Thanks for your suggestions. 
Best
Hsiao-Lin

**Comment by shiauck** [comment]
Hi Hsiao-Lin,

Currently, the scanner have no parameter to output reads containing both 5' and 3' adaptor.
Thank you for your suggestion and I'll discuss this with my mentor.

For your sample running, could you provide the logs files or some first several rows of the result files ?
The curator never access/touch multiple file at the same time to avoid ulimit issues.

Is it convenient to try running a small batch of your sample ?
Like copy the fist 50 or 100 fastq files to a separated folder and run scNanoGPS to see whether you can get result from small batch.

Hope this help.

Regards,
Cheng-Kai

**Comment by wanghlv** [comment]
[sample5.zip](https://github.com/user-attachments/files/16336945/sample5.zip)

Hi Cheng-Kai, Thank you for a quick response. I've taken just the 10000 read from one of my sample and still noting written out to tmp. So I don't think it's the ulimit issue. 

I've attached the entire run folder - Would you mind taking a look. 

Below is how I run each of the steps: 

        python3 ${NANO}/other_utils/read_length_profiler.py -i ${fqD} &>runlog/step1_read_length.log &

        python3 ${NANO}/scanner.py -i ${fqD} -t ${THREAD} --a5 ${a5} --a3 ${a3} --lCB 16 --lUMI 12 \
       --min_read_length 100 --batching_no 10000 --scanning_region 200 &>runlog/step2_scan.log &

        python3 ${NANO}/assigner.py --lCB 16 &>runlog/step3_assign.log &

        python3 ${NANO}/curator.py --keep_meta 1 --ref_genome ${FA} --idx_genome ${FAindex} -t ${THREAD} &>runlog/step4_curator.log &

Thanks so much

Hsiao-Lin

**Comment by shiauck** [comment]
Hi Hsiao-Lin,

Your commands look good except the last "&" symbol, which means background running without waiting.
Please make sure the previous command is done when you're running the next command.

Please try the following modified script:
```
    python3 ${NANO}/other_utils/read_length_profiler.py -i ${fqD} &>runlog/step1_read_length.log &

    python3 ${NANO}/scanner.py -i ${fqD} -t ${THREAD} --a5 ${a5} --a3 ${a3} --lCB 16 --lUMI 12 \
   --min_read_length 100 --batching_no 10000 --scanning_region 200 &>runlog/step2_scan.log

    python3 ${NANO}/assigner.py --lCB 16 &>runlog/step3_assign.log

    python3 ${NANO}/curator.py --keep_meta 1 --ref_genome ${FA} --idx_genome ${FAindex} -t ${THREAD} &>runlog/step4_curator.log
```

You can run "read_length_profiler.py" in background because this script is to draw the read length distribution as a QA, and it won't effect the following steps.

Hope this helps.

Regards,
Cheng-Kai

**Comment by wanghlv** [comment]
Hi Cheng-kai, Yes, I have a wait commend in between all the steps, sorry I copy the lines without the wait in my shell. Thanks for pointing out. I have also run it without the "&". Still there are no files written into the tmp folder. : ( Thanks so much. Hsiao-Lin

**Comment by shiauck** [comment]
Hi Hsiao-Lin,

Is it convenient to provide the following log and meta files ?
(1) scanner.log.txt
(2) assigner.log.txt
(3) curator.log.txt
(4) a couple of lines of processed.fastq.gz
(5) a couple of lines and total row number of CB_counting.tsv.gz
(6) a couple of lines and total row number of CB_merged_list.tsv.gz

Cheng-Kai

**Comment by wanghlv** [comment]
Hi, 
Of course, thank you so much for your help!!

The log files are attached.
[assigner.log.txt](https://github.com/user-attachments/files/16337968/assigner.log.txt)
[curator.log.txt](https://github.com/user-attachments/files/16337969/curator.log.txt)
[scanner.log.txt](https://github.com/user-attachments/files/16337970/scanner.log.txt)

(4) 
$ head -16 processed.fastq
@787f22e8-d4ab-4ac3-b479-9eca9dc54246   st:Z:2023-12-15T11:05:43.907+00:00      RG:Z:ebe23c139e2d70831cd56987a085756d4e356783_dna_r9.4.1_e8_sup@v3.6    DS:Z:gpu:NVIDIA A100-SXM4-40GB
TTTTTTTTTTTTTTTTTTTTTTTTCCAGTGATAGATCTTTGTAGTGCTTTTTTTCCTTTAGCATTCCCGTGTGTGCTGATCATCCC
+
.269:;;;<==>?@ACEGK>>898;@>==>>@;@?<@DDC@A8:349=;3/+))*)*--267><<<=>A9@)))))9====DCDDC
@c57b28dd-b9c6-458b-a3e9-6b94559b750a   st:Z:2023-12-15T11:05:42.583+00:00      RG:Z:ebe23c139e2d70831cd56987a085756d4e356783_dna_r9.4.1_e8_sup@v3.6    DS:Z:gpu:NVIDIA A100-SXM4-40GB
ATTTTTTTTTTTTTTTTTTTTTTTTTGTTTCAGCTTTGCAACCATACTCCCCGGAACCCGAGAACTGGTTTCCGGAAGCTGCCCGGCGGGTCATGGGAATAACGCCGCCGCATCGCTCTCGGTCGGCATCGTTTATGGTCGGAACTACGACGGTATCTGATCGTCTTCGAACCTCCGACTTTCGTTCTTGATTAATGAAAACATTTCATGGCAAATGCTTTCGCTCTGGTCCGTCTTGCGCCGGTCGCATTTCACCTCTAGCGGCGCAATACGAATGCCCCCGGCCGTCCTCTTAATCATGGCCTCAGTTCGAAAACCAACAAAATAGAACCGCGGTCTATTCCATTATTCCTAGCTGCGGTATCCAGGCGGCTCGGGCCTGCTTTGAACACTCTAATTTTTTCAGTAAACGCTTCGGGCCCCGCCCC
+
5552>>>;::87788766531.,+*().246)))67:1<8787.----/3865-.56842//.,,+&&&.651.)((&&()*4005;////1-+****+:;=<9999::88:9<..'%%%%%'&&&'''(++.-,1878;::::<=66656..../754777////5;:9898876546865/--.24<<>>>>:99/..-,+))''&'&&'**)*233113337844354200-,+**''()(((%%%%&&-03223101:988889;99::9<<88311.-///,,3.-..0003:==<;:776(((--)**<===;99::;>=9544436555643346999999:::888899833/0011/115966667...0033334335561(''''&'(+-+()*'''.223333544374345459.
@0ea0f838-2b28-4701-a620-a916331bd0fd   st:Z:2023-12-15T11:05:44.764+00:00      RG:Z:ebe23c139e2d70831cd56987a085756d4e356783_dna_r9.4.1_e8_sup@v3.6    DS:Z:gpu:NVIDIA A100-SXM4-40GB
TTTTTTTTTTTTTTTTTTTTTTCGTCACTACCTCCCCGGGTCGGGAGTGGGTAATTTGCGCGCCTGCTGCCTTCCTTGATGTGGTAGCCGCGTTTCTCAGGCTCCCTCTCCGGAATCGAACTCCCGATTCCCCGTCACCCGTGGTCACCATGGTAGGCACGGCGACTACCATCGAAAGTTGATAGGGCAGACGTTCGAATGTCGTCGCCGCCACGCCC
+
9:;<=>>?@AAAABAAB@?5544666999866>6;86;<;;;<<;9=9:::<C5=>>:77778:9;;:72+)))(()798879965/-,++))((*--.895567988557:=<;9:1------.9?A>===<>>899:;??@><<<=A9753112674443347::989645743,.6:<<:;::=<:;;:9***0,-.889>65555;95100145
@17ed491d-d69c-4b8e-90c4-765f14b7c664   st:Z:2023-12-15T11:05:52.952+00:00      RG:Z:ebe23c139e2d70831cd56987a085756d4e356783_dna_r9.4.1_e8_sup@v3.6    DS:Z:gpu:NVIDIA A100-SXM4-40GB
GTTATTTTTTTTTTTTTTTTTTTTTTTTTTGTCACTACCCCCTCCCCGGGTCGGGAGTGGGTAATTTGCGCGCCTGCTGCCTTCCTTGGATGTGGTAGCCGTTTCTCAGGCTCCCTCTCCGAATCGAACCCCGATTCCCCGTCACCCGTGGTCACCATGGTGGCACGGCGACTACCATCGAAAGTTGATAGGGCAGACGCCCGAATGGGTCGTCGCCGCCACGCCC
+
1000+-.379;>@CDKHGGCCDFDB>911,,)&&&)'''*.1<1?A?FEC<==60/.,10.)%%&(()),,///1434411/1068=?>97778889666779>??@:952-/1014++,N@BAA<6)))))9O=:::<BEE>>=>?DFGP@@?=3-)'&%2ABAFCDKGCABDBEB2286311113358=:>??:943112=?>=>>>@AEA@>>@B@<;>DBCB

(5) CB_counting: 
$ wc -l CB_counting.tsv
7496 CB_counting.tsv

$ head -11 CB_counting.tsv
idx     BC      UMI     log10_idx       log10_UMI       med_log10_slope log10_slope
1       CACTTTGTCATGTCAA        22      0.0     1.3424226808222062
2       TTACCTGTCATTACGA        9       0.3010299956639812      0.9542425094393249      1.2895066171949847      1.2895066171949847
3       ATATGCATCTGCAAGT        8       0.47712125471966244     0.9030899869919435      0.2904887086485455      0.2904887086485455
4       ATCAAGACACGTGCTG        7       0.6020599913279624      0.8450980400142568      0.46416306545102515     0.46416306545102515
5       TCTAATCTCATAGACC        7       0.6989700043360189      0.8450980400142568      0.0     0.0
6       GGTAAGGGTCACAAAT        7       0.7781512503836436      0.8450980400142568      0.0     0.0
7       GCTGCATCAAACCTTG        7       0.8450980400142568      0.8450980400142568      0.0     0.0
8       TACTTCGTCCGTGACA        7       0.9030899869919435      0.8450980400142568      0.0     0.0
9       CTCCGGACATCGCTCC        7       0.9542425094393249      0.8450980400142568      0.0     0.0
10      GTTACCTGTTCCTGTG        6       1.0     0.7781512503836436      1.4630782591069045      1.4630782591069045

(6) CB_merge: 
$ wc -l CB_merged_list.tsv
1199 CB_merged_list.tsv

$ head CB_merged_list.tsv
Representative cell barcode id: included cell barcode id
1: 1
10: 10; 900
100: 100
1000: 1000
1001: 1001
1002: 1002
1003: 1003
1004: 1004
1005: 1005

Thank you so much again!

Best, 
Hsiao-Lin
