### ISSUE TITLE
Error while testing currator.py

### ISSUE THREAD

**Issue by alihamraoui** [gaolabtools/scNanoGPS#4]
Hi @gaobio,
Thank you for developing scNanoGPS pipeline!
I am wondering if you can advise why I get this error when trying to run the test example: 

`Mapping reads for each individual cell barcode ...
[E::hts_open_format] Failed to open file tmp/GCTTACCTCAGGTCCA.unsorted.bam
samtools sort: can't open "tmp/GCTTACCTCAGGTCCA.unsorted.bam": No such file or directory
[E::hts_open_format] Failed to open file tmp/GCTTACCTCAGGTCCA.minimap2.bam
samtools index: failed to open "tmp/GCTTACCTCAGGTCCA.minimap2.bam": No such file or directory
[E::hts_open_format] Failed to open file tmp/GCTTACCTCAGGTCCA.minimap2.bam
Traceback (most recent call last):
  File "curator.py", line 173, in <module>
    os.path.join(options.tmp_dir, fq_pref[0]) + ".high_softclipping.bam")
  File "/export/home1/ScNaUmi-seq_B2022/scNanoGPS/curator_core/curator_io.py", line 44, in filter_softclipping
    bam_i = pysam.AlignmentFile(input_bam,  "rb")
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 940, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file 'tmp/GCTTACCTCAGGTCCA.minimap2.bam': No such file or directory`

This is the Minimap2 output log for the first cell: 

`[WARNING][1;31m Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index.[0m`
`[M::main::0.249*1.02] loaded/built the index for 1 target sequence(s)`
`[M::mm_mapopt_update::0.322*1.02] mid_occ = 238`
`[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1`
`[M::mm_idx_stat::0.374*1.01] distinct minimizers: 5012420 (87.89% are singletons); average occurrences: 1.472; average spacing: 6.888; total length: 50818468`
`[M::worker_pipeline::1.114*3.34] mapped 229 sequences`
`[M::main] Version: 2.24-r1122`
`[M::main] CMD: minimap2 -ax splice -t 8 example/GRCh38_chr22.mmi tmp/GCTTACCTCAGGTCCA.fastq.gz`
`[M::main] Real time: 1.130 sec; CPU: 3.740 sec; Peak RSS: 1.324 GB`

I have correctly installed all required dependencies. BTW, This example works on my local machine (macOS) but not in my Linux server. 

I would be very grateful if you could provide a Docker file or a complete conda env file!

Thank you
Ali

**Comment by shiauck** [comment]
Hi Ali,

Thanks for using scNanoGPS.
We developed scNanoGPS under Linux environment.
Thank you for letting us know there's an environmental incompatibility under MacOS.
I'll try to fix it.

Regards,
CK

**Comment by shiauck** [comment]
Hi Ali,

I've tried our pipeline in my iMac, and it works smoothly.

Could you try the following command for me to see what you get ?
`python3 curator.py -t 2 --ref_genome example/GRCh38_chr22.fa.gz --idx_genome example/GRCh38_chr22.mmi --keep_meta 1`
Adding the parameter "keep_meta 1" allows you to keep the meta files for tracking.
Please let me know the file names having prefix/barcode "GCTTACCTCAGGTCCA" or any other files, so that I can try to find out the bug.
Thank you in advance.

Regards,
Cheng-Kai

**Comment by alihamraoui** [comment]
Hi shiauck,
Thank you for your response. I think there is a misunderstanding, I actually meant that the bug occurs under Linux environment. 
Thank you in advance,
Ali

**Comment by shiauck** [comment]
Hi Ali,

We develop and check the pipeline under CentOS and Ubuntu.
Could you please run the command under your Linux environment for me ?
`python3 curator.py -t 2 --ref_genome example/GRCh38_chr22.fa.gz --idx_genome example/GRCh38_chr22.mmi --keep_meta 1`
So that I can try to trace the bug for you.

Thank you for you suggestions for Docker or Conda env.
I'll discuss with my mentor about your suggestions.

Regards,
CK

**Comment by alihamraoui** [comment]
Hi shiauck,
My server is under Ubuntu 20.04.5 LTS. 
I ran your command and I get the error : 

`Mapping reads for each individual cell barcode ...`
`rm: impossible de supprimer 'tmp/GCTTACCTCAGGTCCA.unsorted.bam': Aucun fichier ou dossier de ce type`
`[E::hts_open_format] Failed to open file tmp/GCTTACCTCAGGTCCA.minimap2.bam`
`Traceback (most recent call last):`
`  File "curator.py", line 173, in <module>`
`    os.path.join(options.tmp_dir, fq_pref[0]) + ".high_softclipping.bam")`
`  File "/export/home1/ScNaUmi-seq_B2022/scNanoGPS/curator_core/curator_io.py", line 44, in filter_softclipping`
`    bam_i = pysam.AlignmentFile(input_bam,  "rb")`
`  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__`
 ` File "pysam/libcalignmentfile.pyx", line 940, in pysam.libcalignmentfile.AlignmentFile._open`
`FileNotFoundError: [Errno 2] could not open alignment file `tmp/GCTTACCTCAGGTCCA.minimap2.bam`: No such file or directory`
`[E::hts_open_format] Failed to open file tmp/GCTTACCTCAGGTCCA.unsorted.bam
samtools sort: can't open "tmp/GCTTACCTCAGGTCCA.unsorted.bam": No such file or directory`
`[E::hts_open_format] Failed to open file tmp/GCTTACCTCAGGTCCA.sam
samtools view: failed to open "tmp/GCTTACCTCAGGTCCA.sam" for reading: No such file or directory`
`[E::hts_open_format] Failed to open file tmp/GCTTACCTCAGGTCCA.minimap2.bam
samtools index: failed to open "tmp/GCTTACCTCAGGTCCA.minimap2.bam": No such file or directory`

I get two files with prefix "GCTTACCTCAGGTCCA" in tmp dir : 

- GCTTACCTCAGGTCCA.fastq.gz
- GCTTACCTCAGGTCCA.minimap2.log.txt

Thnak you again for the considerable help!
Ali

**Comment by alihamraoui** [comment]
I also gziped fasta genome example/GRCh38_chr22.fa.gz before running the command : `python3 curator.py -t 2 --ref_genome example/GRCh38_chr22.fa --idx_genome example/GRCh38_chr22.mmi --keep_meta 1 `
but that was not supposed to be a trouble.

**Comment by shiauck** [comment]
It looks like that the minimap2 isn't working.
Could you try the following command for me?
`minimap2 -ax splice -t 8 example/GRCh38_chr22.mmi tmp/GCTTACCTCAGGTCCA.fastq.gz`
This is the manual mapping command with minimap2 containing inside curator.

**Comment by alihamraoui** [comment]
Your command seems to be working : 
I got a SAM output with:
`
[M::worker_pipeline::1.192*3.29] mapped 229 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -ax splice -t 8 example/GRCh38_chr22.mmi tmp/GCTTACCTCAGGTCCA.fastq.gz
[M::main] Real time: 1.210 sec; CPU: 3.934 sec; Peak RSS: 1.324 GB
`

**Comment by alihamraoui** [comment]
I also printed and tested manually all CMD in currator.py pipeline (minimap2, samtools ..). 
there seems to be no particular error.

**Comment by shiauck** [comment]
Cool.
I think the bug is using subprocess Popen under Ubuntu.
https://stackoverflow.com/questions/57863648/subprocess-popen-working-on-windows-and-not-on-ubuntu
I'll find a way to fix it.

**Comment by alihamraoui** [comment]
Cool, 
Thak you @shiauck for the support! 👍 👍 👍 
Regards,
Ali

**Comment by anshulbudhraja** [comment]
> Hi Ali,
> 
> I've tried our pipeline in my iMac, and it works smoothly.
> 
> Could you try the following command for me to see what you get ? `python3 curator.py -t 2 --ref_genome example/GRCh38_chr22.fa.gz --idx_genome example/GRCh38_chr22.mmi --keep_meta 1` Adding the parameter "keep_meta 1" allows you to keep the meta files for tracking. Please let me know the file names having prefix/barcode "GCTTACCTCAGGTCCA" or any other files, so that I can try to find out the bug. Thank you in advance.
> 
> Regards, Cheng-Kai

Hi Cheng-Kai,

I'm facing the same error in Linux and will gladly await your solution to it.
Could you also edit the documentation and mention that the option --keep_meta is supposed to have a numeric argument as input. Wasn't clear on how to use --keep_meta before I saw this thread. 

Thanks for developing the tool!
Regards, 
Anshul

**Comment by shiauck** [comment]
Hi Ali and Anshul,

I've done a patch for Ubuntu.
And I also checked it under CentOS 7, MacOS (Darwin Kernel 22.3.0), and Ubuntu 22.04.2.
Could you please download the pipeline again and give it a trial ?
Please lemme know if there's any problem occur under Ubuntu environment.
Thank you so much.
I really appreciate your feedback.

Regards,
Cheng-Kai

**Comment by alihamraoui** [comment]
Hi @shiauck,
That is working 👍 Thank you so much!

Regards,
Ali

**Comment by shiauck** [comment]
Cool.
I'm glad that I can help.
I'm closing this issue.
Let me know if there's any bugs.
Thanks in advance. :)
