### ISSUE TITLE
Is the toolkit only compatible with 3 prime adapters?

### ISSUE THREAD

**Issue by sirselim** [gaolabtools/scNanoGPS#5]
I was testing scNanoGPS on some 5 prime data that I have and noticed that it is only picking up <10% of reads at the scanner step, and only reporting on the 3 prime adapter identified. It's not readily clear, but from this observation and the manuscript it seems that it's currently only working for 3 prime data?

**Comment by shiauck** [comment]
Hi,
Thanks for trying our tool.

Our original design is putting cell barcode next to the 3' adapter.
If your cell barcode is designed next to the 5' adapter, please try the parameter "--a3" and put your 5' adapter sequence here.
And then use "--a5" to handle your 3' adapter.

In addition, please check the length of your cell barcode and UMI,
and assign them with parameters "--lCB" and "--lUMI" respectively if needed.
Hope this help.
