### ISSUE TITLE
suggestion - ressources needed

### ISSUE THREAD

**Issue by reJELIN** [gaolabtools/scNanoGPS#6]
Hi,

Thank you for your work and this tool that is very useful.

Would it be possible to have more info about current ressources needed for each steps and an approximate time of run ? Because i'm working in a HPC and i must share my ressources with other so i can't use 400Go of RAM for one entire week.

Thank you in advance

**Comment by reJELIN** [comment]
Thank you for the benchmarking !

By any chance did you compare your results with sicelore ? that is mainly doing the same job as scNanoGPS ? It would be interesting to compare both results.

**Comment by shiauck** [comment]
Hi,

Thanks for the suggestion.
Actually we used sicelore v1 almost two years before, but somehow we could not obtain correct result.
I notice that sicelore release v2.
I'll take a chance to try sicelore v2.
Thank you in advance.
I really appreciate it.

Regards,
Cheng-Kai
