### ISSUE TITLE
IsoSeq and MASseq

### ISSUE THREAD

**Issue by yoavhadas** [gaolabtools/scNanoGPS#7]
Hello,
Can scNanoGPS be used with data generated by PacBio platforms such as scIsoSeq or MASseq?

Thank you
Yoav

**Comment by shiauck** [comment]
Hi Yoav,

If the fastq read architecture is the same as mentioned in our paper, then scNanoGPS could be used to process the single cell long-read data.
Please let me know if you have any trouble running scNanoGPS and I'll do my best.
Good luck.

Regards,
CK
